export { default as Contact } from './Contact'
export { default as Heading } from './Heading'
export { default as OpenSource } from './OpenSource'
export { default as Projects } from './Projects'
export { default as Skills } from './Skills'
